# Generated by Django 5.0.6 on 2024-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift_duration_hours',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
