# Generated by Django 5.0.6 on 2024-07-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_alternative_email_user_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='educational_certificates',
            field=models.FileField(blank=True, null=True, upload_to='educational_certificates'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to='identity_proof'),
        ),
        migrations.AlterField(
            model_name='user',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='offer_letter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='professional_certifications',
            field=models.FileField(blank=True, null=True, upload_to='professional_certifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utility_bills',
            field=models.FileField(blank=True, null=True, upload_to='utility_bills'),
        ),
    ]
