# Generated by Django 5.0.6 on 2024-10-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_working_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='basic_salary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
