# Generated by Django 5.0.6 on 2024-11-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_basic_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
