# Generated by Django 5.0.6 on 2024-11-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to='experience_certificate'),
        ),
    ]
