# Generated by Django 5.0.6 on 2024-11-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_experience_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
