# Generated by Django 5.0.6 on 2024-11-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_tax_number',
        ),
    ]
