# Generated by Django 5.0.6 on 2024-11-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_shift_end_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='college_grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='college_major_subject',
        ),
        migrations.RemoveField(
            model_name='user',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='college_year_graduation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='master_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='master_degree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='master_grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='master_graduation_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='master_major_subject',
        ),
        migrations.RemoveField(
            model_name='user',
            name='master_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phd_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phd_degree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phd_dissertation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phd_graduation_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phd_major_subject',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phd_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phd_supervisor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_major_subject',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_year_graduation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='schoool_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='undergraduate_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='undergraduate_degree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='undergraduate_grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='undergraduate_graduation_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='undergraduate_major_subject',
        ),
        migrations.RemoveField(
            model_name='user',
            name='undergraduate_name',
        ),
        migrations.AddField(
            model_name='user',
            name='bachelors_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='diploma_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intermediate_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_experience',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='masters_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='matric_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phd_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
