# Generated by Django 5.0.6 on 2024-12-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_college_city_remove_user_college_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee_view_access', models.BooleanField(default=False)),
                ('employee_edit_access', models.BooleanField(default=False)),
                ('employee_delete_access', models.BooleanField(default=False)),
                ('employee_edit_access_delete', models.BooleanField(default=False)),
                ('ip_view_access', models.BooleanField(default=False)),
                ('ip_edit_access', models.BooleanField(default=False)),
                ('ip_delete_access', models.BooleanField(default=False)),
                ('ip_edit_access_delete', models.BooleanField(default=False)),
                ('role_view_access', models.BooleanField(default=False)),
                ('role_edit_access', models.BooleanField(default=False)),
                ('role_delete_access', models.BooleanField(default=False)),
                ('role_edit_access_delete', models.BooleanField(default=False)),
                ('applicant_view_access', models.BooleanField(default=False)),
                ('applicant_edit_access', models.BooleanField(default=False)),
                ('applicant_delete_access', models.BooleanField(default=False)),
                ('applicant_edit_access_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
