# Generated by Django 5.0.6 on 2024-12-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='applicant_edit_access_delete',
            new_name='applicant_add_access',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='employee_edit_access',
            new_name='employee_add_access',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='ip_edit_access_delete',
            new_name='ip_add_access',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_edit_access_delete',
            new_name='role_add_access',
        ),
    ]
