# Generated by Django 5.0.6 on 2024-07-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='break_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='remainig_hours',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=3),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='total_hours_completed',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=3),
        ),
    ]
