# Generated by Django 5.0.6 on 2024-07-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0002_alter_attendancemodel_break_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='total_hours_completed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='working_hours',
            field=models.IntegerField(default=0),
        ),
    ]
