# Generated by Django 5.0.6 on 2024-07-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0003_alter_attendancemodel_total_hours_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='shift_time',
            field=models.TimeField(null=True),
        ),
    ]
