# Generated by Django 5.0.6 on 2024-07-06 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0004_alter_attendancemodel_shift_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodel',
            name='remainig_hours',
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='remaining_hours',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='break_hours',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='total_hours_completed',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='working_hours',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
