# Generated by Django 5.0.6 on 2024-07-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0007_alter_attendancemodel_break_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='break_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='break_type',
            field=models.CharField(blank=True, default='System Generated', max_length=200, null=True),
        ),
    ]
