# Generated by Django 4.2.14 on 2024-07-13 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm_app', '0008_attendancemodel_break_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodel',
            name='break_comments',
        ),
        migrations.RemoveField(
            model_name='attendancemodel',
            name='break_type',
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='is_time_out_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='time_out_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeBreakRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(blank=True, default='System Generated', max_length=200, null=True)),
                ('break_comments', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='break_time_stamp',
            field=models.ManyToManyField(blank=True, null=True, to='hrm_app.employeebreakrecords'),
        ),
    ]
