# Generated by Django 4.2.14 on 2024-07-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0009_remove_attendancemodel_break_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebreakrecords',
            name='is_break_end',
            field=models.BooleanField(default=False),
        ),
    ]
