# Generated by Django 5.0.6 on 2024-08-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0013_alter_attendancemodel_break_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
