# Generated by Django 5.0.6 on 2024-10-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0014_attendancemodel_is_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position_applied_for', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('cnic', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(max_length=200)),
                ('expected_salary', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=200)),
                ('emergeny_contact_number', models.CharField(max_length=200)),
                ('when_join_us', models.CharField(max_length=200)),
                ('shift_availablity', models.JSONField()),
                ('matric_details', models.JSONField()),
                ('intermediate_details', models.JSONField()),
                ('bachelors_details', models.JSONField(blank=True, null=True)),
                ('masters_details', models.JSONField(blank=True, null=True)),
                ('phd_details', models.JSONField(blank=True, null=True)),
                ('diploma_details', models.JSONField(blank=True, null=True)),
                ('job_experience', models.JSONField()),
                ('upload_profile', models.FileField(blank=True, null=True, upload_to='profile-picture')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume')),
                ('declaration', models.BooleanField(default=False)),
            ],
        ),
    ]
