# Generated by Django 5.0.6 on 2024-10-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0015_applicantdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
