# Generated by Django 5.0.6 on 2024-10-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0016_applicantdetails_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='email_address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
