# Generated by Django 5.0.6 on 2024-10-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0018_systemattendancemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemattendancemodel',
            name='remaining_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
