# Generated by Django 5.0.6 on 2024-10-22 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0019_alter_systemattendancemodel_remaining_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbAttendnace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_table', models.TimeField()),
                ('auto_assign', models.CharField(max_length=200, null=True)),
                ('on_duty', models.CharField(max_length=200)),
                ('off_duty', models.CharField(max_length=200)),
                ('clock_in', models.CharField(blank=True, max_length=200, null=True)),
                ('clock_out', models.CharField(blank=True, max_length=200, null=True)),
                ('normal', models.CharField(blank=True, max_length=200, null=True)),
                ('real_time', models.CharField(blank=True, max_length=200, null=True)),
                ('late', models.CharField(blank=True, max_length=200, null=True)),
                ('early', models.CharField(blank=True, max_length=200, null=True)),
                ('absent', models.CharField(blank=True, max_length=200, null=True)),
                ('ot_time', models.CharField(blank=True, max_length=200, null=True)),
                ('work_time', models.CharField(blank=True, max_length=200, null=True)),
                ('exception', models.CharField(blank=True, max_length=200, null=True)),
                ('must_cin', models.BooleanField(default=False)),
                ('must_cout', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('ndays', models.CharField(blank=True, max_length=200, null=True)),
                ('weekend', models.CharField(blank=True, max_length=200, null=True)),
                ('holiday', models.CharField(blank=True, max_length=200, null=True)),
                ('att_time', models.TimeField(blank=True, null=True)),
                ('ndays_ot', models.CharField(blank=True, max_length=200, null=True)),
                ('weekend_ot', models.CharField(blank=True, max_length=200, null=True)),
                ('holiday_ot', models.CharField(blank=True, max_length=200, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
