# Generated by Django 5.0.6 on 2024-10-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0020_thumbattendnace'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbattendnace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
