# Generated by Django 5.0.6 on 2024-10-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0023_alter_thumbattendnace_time_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbattendnace',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
