# Generated by Django 5.0.6 on 2024-10-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0024_alter_thumbattendnace_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='cnic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='contact_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='emergeny_contact_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='intermediate_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='job_experience',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='marital_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='matric_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='position_applied_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='shift_availablity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='when_join_us',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
