# Generated by Django 4.1.4 on 2024-10-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0025_alter_applicantdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='other_mobile_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
