# Generated by Django 4.1.4 on 2024-11-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0026_applicantdetails_other_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
