# Generated by Django 5.0.6 on 2024-11-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0028_applicantdetails_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
