# Generated by Django 4.1.4 on 2024-11-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0029_applicantdetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantdetails',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantdetails',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
