# Generated by Django 5.0.6 on 2024-11-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0030_applicantdetails_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
