# Generated by Django 5.0.6 on 2024-11-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0031_applicantdetails_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='shortlisted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
