# Generated by Django 5.0.6 on 2024-11-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0032_applicantdetails_shortlisted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='status',
            field=models.CharField(blank=True, default='In Process', max_length=200, null=True),
        ),
    ]
