# Generated by Django 4.1.4 on 2024-11-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0033_applicantdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantdetails',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantdetails',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
