# Generated by Django 5.0.6 on 2024-11-30 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0036_applicantdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicanthistory',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm_app.applicantdetails'),
        ),
    ]
