# Generated by Django 5.0.6 on 2024-11-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0037_applicanthistory_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicanthistory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
