# Generated by Django 5.0.6 on 2024-12-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0038_applicanthistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanthistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicanthistory',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
