# Generated by Django 5.0.6 on 2025-02-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0039_alter_applicanthistory_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('weekday', models.CharField(max_length=20)),
                ('timetable', models.CharField(max_length=100)),
                ('clock_in_date', models.DateField(blank=True, null=True)),
                ('clock_in_time', models.TimeField(blank=True, null=True)),
                ('clock_in_source', models.CharField(blank=True, max_length=100, null=True)),
                ('clock_out_date', models.DateField(blank=True, null=True)),
                ('clock_out_time', models.TimeField(blank=True, null=True)),
                ('clock_out_source', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Leave', 'Leave')], max_length=50)),
                ('worked_hours', models.DurationField(blank=True, null=True)),
                ('absent_duration', models.DurationField(blank=True, null=True)),
                ('late_duration', models.DurationField(blank=True, null=True)),
                ('early_leave_duration', models.DurationField(blank=True, null=True)),
                ('break_duration', models.DurationField(blank=True, null=True)),
                ('leave_duration', models.DurationField(blank=True, null=True)),
                ('overtime_duration', models.DurationField(blank=True, null=True)),
                ('workday_overtime_duration', models.DurationField(blank=True, null=True)),
                ('weekend_overtime_duration', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
