# Generated by Django 5.0.6 on 2025-02-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0040_machineattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
