# Generated by Django 5.0.6 on 2025-02-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0041_machineattendance_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineattendance',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
    ]
