# Generated by Django 5.0.6 on 2025-02-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0042_alter_machineattendance_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineattendance',
            name='attendance_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
