# Generated by Django 5.0.6 on 2025-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0044_googleleads'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleleads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
