# Generated by Django 4.1.4 on 2025-02-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0045_googleleads_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleleads',
            name='temp_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
